spring:
  application:
    name: blogApp

  data:
    mongodb:
      uri: mongodb+srv://vedantgadekar77:vedant77@cluster0.vtijg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journalDB

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              index: DEBUG
